#! /bin/bash
echo Saving image to tar...
docker save -o ../bin/images/starmixinfo.tar starmixinfo:latest
echo Done!
echo Uploading tar to server...
scp -C ../bin/images/starmixinfo.tar ubuntu@starmix.devsprime.com:/var/dev/docker/images/
echo Uploaded!
echo Loading tar as image and restarting server...
ssh ubuntu@starmix.devsprime.com '\
    sudo docker load -i /var/dev/docker/images/starmixinfo.tar; \
    sudo docker container stop wserv_starmixinfo;
    sudo docker container rm wserv_starmixinfo; \
    sudo docker container run \
        --name wserv_starmixinfo \
        --network webserver_nw \
        --restart always \
        -v /var/dev/docker/volumes/starmixinfo/logs:/app/Logs \
        -v /var/dev/docker/volumes/starmixinfo/uploads:/app/wwwroot/uploads \
        -d starmixinfo:latest; \
    sudo docker image prune -f'
echo Done! Webserver has been re-deployed
