#! /bin/bash
CONTAINER="webserver"
WEBSERVER_VOLUMES="/var/dev/docker/volumes/starmixinfo"

echo Saving image to tar...
docker save -o ../bin/images/starmixinfo.tar starmixinfo:latest
echo Done!
echo Uploading tar to server...
scp -C ../bin/images/starmixinfo.tar ubuntu@starmix.devsprime.com:/var/dev/docker/images/
echo Uploaded!
echo Loading tar as image and restarting server...
ssh ubuntu@starmix.devsprime.com '\
    sudo docker load -i /var/dev/docker/images/starmixinfo.tar; \
    sudo docker container stop webserver;
    sudo docker container rm webserver; \
    sudo docker container run \
        --name webserver \
        --network webserver_nw \
        --restart always \
        -v $WEBSERVER_VOLUMES/logs:/app/Logs \
        -v $WEBSERVER_VOLUMES/uploads:/app/wwwroot/uploads \
        -d starmixinfo:latest; \
    sudo docker image prune -f'
echo Done! Webserver has been re-deployed
